Completed Css positioning | Siriphum Chiaravanont
S-Chiaravanont/c1022-code-solutions pull request #21
Opened 2022-10-14 08:07 UTC by S-Chiaravanont

![Oct-13-2022 23-54-53](https://user-images.githubusercontent.com/36710918/195795700-1dd5b75e-5440-4851-9f3e-ca089f2b52f6.gif)
<img width="1202" alt="Screen Shot 2022-10-13 at 6 55 57 PM" src="https://user-images.githubusercontent.com/36710918/195795705-3f221c0f-c163-4e64-8a19-00aa913f4fbe.png">
<img width="931" alt="Screen Shot 2022-10-14 at 1 04 43 AM" src="https://user-images.githubusercontent.com/36710918/195795706-4db8e7b8-df89-43a1-8298-fa741e8ac58e.png">

2022-10-14 21:00 UTC, codingcodymiller requested changes

2022-10-14 21:00 UTC, codingcodymiller commented on css-positioning/fixed.css
> +  right: 400px;
Woah, this is a **_big_** movement. Instead, you should make the element `width: 100%` so that `text-align` can do the work of centering the text.

2022-10-15 15:20 UTC, S-Chiaravanont commented
<img width="1234" alt="Screen Shot 2022-10-15 at 8 17 50 AM" src="https://user-images.githubusercontent.com/36710918/195994278-e4580fbc-8d36-4ed5-a4f0-df5ee2256cc9.png">

2022-10-17 16:46 UTC, codingcodymiller approved these changes

2022-10-17 16:52 UTC, merged