Object manipulation 3 | Siriphum Chiaravanont
S-Chiaravanont/c1022-code-solutions pull request #66
Opened 2022-11-09 00:03 UTC by S-Chiaravanont

![Screen Shot 2022-11-08 at 3 59 40 PM](https://user-images.githubusercontent.com/36710918/200702701-b79d3382-db34-4157-b0fb-d8d541b47126.png)

2022-11-11 17:45 UTC, codingcodymiller requested changes

2022-11-11 17:45 UTC, codingcodymiller commented on object-manipulation-3/main.js
> +];
Instead of writing all these out by hand, I would make an array of suits and an array of ranks, and use those to generate the deck 🤓

2022-11-11 17:45 UTC, codingcodymiller commented on object-manipulation-3/main.js
> +}
Why is this necessary?

2022-12-01 18:57 UTC, thebearingedge approved these changes

2022-12-01 19:31 UTC, merged